### ISSUE TITLE
Can I get player voice data?

### ISSUE THREAD

**Issue by Foodust** [Vallerian/MelodyMine#106]
You may lack English using a translator.
I'm looking for a way to process the player's voice.
Is it possible to import this data when the player speaks in any way?
Or you can chat out the voice the player is talking about..

**Comment by Vallerian** [comment]
You can receive when the player is talking using the PlayerChangeTalkEvent.
More information: https://docs.sayandev.org/melodymine/api/events/control/playerchangetalkevent

**Comment by Foodust** [comment]
I mean, it's not player data
I want the "voice" data that the player said.

**Comment by Vallerian** [comment]
Currently, there is no such thing in Melodymine, but it has the capability to be added.

**Comment by Foodust** [comment]
If so, are you going to add it to MelodyMine or do you have to work on it separately?
Thank you for your response.

**Comment by Vallerian** [comment]
Currently, this feature will not be added to MelodyMine, but it might be included in the next major update.
