### ISSUE TITLE
Forum request

### ISSUE THREAD

**Issue by exdj158** [Vallerian/MelodyMine#2]
Do you have a forum or contact information? I have some questions and suggestions for improvement

**Comment by Vallerian** [comment]
You can contact with me through Discord.
Discord: .taher7

**Comment by UnknowUser0** [comment]
The tutorial is too difficult to do for a local server

**Comment by Vallerian** [comment]
> The tutorial is too difficult to do for a local server

the installation is easy in new version [2.0.0](https://github.com/Vallerian/MelodyMine/releases/tag/2.0.0)
