### ISSUE TITLE
Voicerange

### ISSUE THREAD

**Issue by DerVerplanteTom** [Vallerian/MelodyMine#25]
Sup, is it possible to add a command which allows you to specify your voicrange for example 8/16 or 32 Blocks

**Comment by Vallerian** [comment]
Hi, You can change it in config file, Also you can change everything about voice.

`
# ------ sound configs ------
3D-sound: true # player voice 3D mode.
hear-lazy: true # default player volume (when 3DSound is "false" you can use this feature).
max-distance: 30 # distance that players can hear each other.
ref-distance: 5  # distance that players can hear each other max volume.
inner-angle: 120 # angle that players can hear each other max volume.
outer-angle: 180 # angle that players can hear each other.
outer-volume: 0.3 # outer angle volume.
`

**Comment by DerVerplanteTom** [comment]
Yeah i saw that but it would be a nice feature if it is possible to do it ingame for each player for example in an roleplay situation

**Comment by Vallerian** [comment]
The feature is examined in the first opportunity, and if there are no issues, this feature will be added to the plugin.
